version: '2.1'

services:
  web-application:
    container_name: web-application
    build: ./
    volumes:
      - './:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '3007:3006' # expose ports - HOST:CONTAINER
  transaction-service:  
    container_name: transaction-service
    build: './services/transaction-worker'
    volumes:
      - './services/transaction-worker:/usr/src/app'
      - './services/transaction-worker/package.json:/usr/src/package.json'
      - './services/transaction-worker:/usr/src/app/node_modules'
    ports:
      - '3000:3000' # expose ports - HOST:CONTAINER
  budget-service:  
      container_name: budget-service
      build: './services/budget-worker'
      volumes:
        - './services/budget-worker:/usr/src/app'
        - './services/budget-worker/package.json:/usr/src/package.json'
        - './services/budget-worker:/usr/src/app/node_modules'
      ports:
        - '7080:7080' # expose ports - HOST:CONTAINER